#!/usr/bin/env bash
# this script takes an arg, (in if), if not: print msge, else: use ping cmd with count 5 and the arg
if [ $# -eq 0 ]; then
  echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
  exit 1
fi

IP_ADDRESS=$1

ping -c 5 $IP_ADDRESS
